#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
#CE CODE N'EXISTE PAS ET NE RESPECTE AUCUN PARADYGME, MERCI DE FERMER LE FICHIER
























































import pygame
from PyQt6.QtGui import QMovie
from PyQt6.QtWidgets import QWidget, QPushButton, QVBoxLayout, QLabel
from PyQt6 import QtWidgets, QtCore, QtGui
import random


class vueSecrete(QWidget):

    def __init__(self):

        super().__init__()

        self.secretLabel = QLabel()
        self.secretLabel2 = QLabel("Oh non, une vilaine erreur :(((((((")

        self.boutonQuitter = QPushButton("Quitter", clicked=lambda:exit())


        self.secretButon = QPushButton("Cliquez ici pour retourner en arrière", clicked=lambda:self.secretFuction())

        self.layout = QVBoxLayout()
        self.setLayout(self.layout)
        self.layout.addWidget(self.secretLabel2)
        self.layout.addWidget(self.secretButon)
        self.layout.addWidget(self.secretLabel)


    def secretFuction(self):

        pygame.init()

        chiffre = random.randint(0,100)


        if chiffre == 32:
            pygame.mixer_music.load("sounds/sound2.mp3")
            self.secretButon.setText("BARBICHETTE !")
            self.movie = QMovie("images/2.gif")
        else:
            pygame.mixer_music.load("sounds/sound1.mp3")
            self.secretButon.setText("TOUDOUTOUDOUTOU !")
            self.movie = QMovie("images/ICU.gif")
        pygame.mixer_music.play(-1)



        self.secretLabel2.clear()
        self.secretButon.setEnabled(False)

        self.secretLabel.setGeometry(QtCore.QRect(25, 25, 200, 200))
        self.secretLabel.setMinimumSize(QtCore.QSize(200, 200))
        self.secretLabel.setMaximumSize(QtCore.QSize(400, 400))
        self.secretLabel.setObjectName("label")
        self.layout.addWidget(self.boutonQuitter)


        self.secretLabel.setMovie(self.movie)
        self.movie.start()

